In [2]:
#import the numpy and defined as np
#input the value of array
#redefine the value of array,begins from the index 1 to the end, and make odd number to be -10
#print the result
import numpy as np
arr = np.array([0,1,2,3,4,5,6,7,8,9])
arr[1: :2] = -10
arr

array([  0, -10,   2, -10,   4, -10,   6, -10,   8, -10])

In [15]:
#import the numpy and defined as np
#input the value of array
#resize all ten values of array and reshape the ten vales as two dimensional array, each line contains 5 values of array.
import numpy as np
arr = np.array([0,1,2,3,4,5,6,7,8,9])
np.resize(arr,10).reshape(2,5)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [11]:
#import the numpy and defined as np
#input the value of array
#find the values of array that greater or equal to 5 and smaller or equal to 12.
#print the result.
import numpy as np
arr = np.array([3,1,6,17,8,42,10,39,25,12,14,42])
arr = arr[(5 <= arr) & (arr <= 12)]
arr

array([ 6,  8, 10, 12])

In [12]:
import numpy as np
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
#import the numpy and defined as np
#input the value of array
#exchange the positions of first and second rows by exchange the index values of array. 
#print the result
import numpy as np
arr = np.arange(9).reshape(3,3)
arr[[0,1]] = arr[[1,0]]
arr

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [19]:
import numpy as np
arr = np.arange(9).reshape(3,3)
arr[[1,0,2], :]
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])