Task one: finds the distinct/unique common items between these two arrays
#import the numpy and defined as np
#input the value of array
#utiliz the intersect1d to find the unique common items between two arrays.

In [4]:
import numpy as np
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
print(np.intersect1d(a,b))

[2 4]


Task two: Create the following 5x3 array
#import the numpy and defined as np
#define the value of array
#utilize for loop to output the results by column.
#print the result

In [23]:
import numpy as np
#output the value from 1 to 15 whose indexs is from 1 to 16, and reshape the output to be 3 rows and 5 column.
#make the output display by column not row, it also means exchange to be 5 rows and 3 column. 
a = np.arange(1,16).reshape(3,5)
for column in a.T:
    print(column)

[ 1  6 11]
[ 2  7 12]
[ 3  8 13]
[ 4  9 14]
[ 5 10 15]


Task three: removes from array a any items that are also present in array b
#import the numpy and defined as np
#input the value of array
#utilize the setdiff1d to find the elements of array a that do not display in array b. 

In [28]:
import numpy as np
a = np.array([12, 5, 7, 15, 3, 1, 8])      
b = np.array([14, 6, 3, 11, 19, 12, 5])
#element display in a but b.
print(np.setdiff1d(a,b))

[ 1  7  8 15]


Task four: create a NumPy array where in you can record the cumulative miles you recorded each day during your trip,show the total miles that you rode each day.
#import the numpy and defined as np
#input the value of array
#build a new arry that is the record begins from second day.

In [57]:
#distance between NYC and Key West is 1933 kilometers.
#there are four days rider did not ride during 35 days trips.
#create a new array record1 that the record the cumulated Km that the rider rode begins from the first day, the ending number is 1933.
#create a new array record2 that the cumulated Km the rider rode from the first day to the last second day,it is the index of record1 from  0 to 33.
#create a nre array record3 that the cumulated Km the rider rode from the second day to the end,it is the index of record1 from 1 to 34.
#to calculate the Km that riders rode for each day as record4. 
import numpy as np
record1 = np.array([90, 170, 280, 340, 400, 400, 470, 550, 600, 650, 700, 700, 770, 840, 880, 920, 960, 1020, 1060, 1140, 1140, 1200, 1260, 1350, 1400, 1470, 1530, 1550, 1600, 1600, 1670, 1750, 1810, 1880, 1933])
record2 = record1[:34]
record3 = record1[1:35]
record4 = record3 - record2
print(record4)

[ 80 110  60  60   0  70  80  50  50  50   0  70  70  40  40  40  60  40
  80   0  60  60  90  50  70  60  20  50   0  70  80  60  70  53]


Task five: Answer questions

In [69]:
import pandas
import numpy as np

# supress scientific notation
np.set_printoptions(suppress = True)

# read the data file from GitHub and convert to a NumPy ndarray object
nyc_water = pandas.read_csv('https://raw.githubusercontent.com/jtopor/DAV-5400/master/Week4/Water_Consumption_In_The_New_York_City.csv').as_matrix()

# verify you have an ndarray object
type(nyc_water)
print(nyc_water)

[[   1979.  7102100.     1512.      213. ]
 [   1980.  7071639.     1506.      213. ]
 [   1981.  7089241.     1309.      185. ]
 [   1982.  7109105.     1382.      194. ]
 [   1983.  7181224.     1424.      198. ]
 [   1984.  7234514.     1465.      203. ]
 [   1985.  7274054.     1326.      182. ]
 [   1986.  7319246.     1351.      185. ]
 [   1987.  7342476.     1447.      197. ]
 [   1988.  7353719.     1484.      202. ]
 [   1989.  7344175.     1402.      191. ]
 [   1990.  7335650.     1424.      194. ]
 [   1991.  7374501.     1469.      199. ]
 [   1992.  7428944.     1369.      184. ]
 [   1993.  7506166.     1368.5     182. ]
 [   1994.  7570458.     1357.7     179. ]
 [   1995.  7633040.     1325.7     174. ]
 [   1996.  7697812.     1297.9     169. ]
 [   1997.  7773443.     1205.5     155. ]
 [   1998.  7858259.     1219.5     155. ]
 [   1999.  7947660.     1237.2     156. ]
 [   2000.  8008278.     1240.4     155. ]
 [   2001.  8024963.5    1184.      148. ]
 [   2002. 

C:\Users\13750\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


What is the maximum yearly NYC consumption of water in millions of gallons per day?

In [82]:
import numpy as np
#import the numpy and defined as np
#define the value of array
nyc_water = np.array([nyc_water])
#extract the max valuse in second column of array
maxValue = max(nyc_water[:,2])


 How many calendar years are represented within this data set? NumPy's shape command is one way to find out.

In [ ]:
#use shape to find the total rows and column of array.
numrows = np.shape(nyc_water)

What is the mean and the standard deviation of the per capita daily water consumption?

In [ ]:
#use mean to find the mean of row 4, index is 3, that is per capita daily water consumption
#use std to find the standard deviation of row 4, index is 3, that is per capita daily water consumption
meanrows = mean(nyc_water[:,3])
sdrows = std(nyc_water[;,3])

What is the increase or decrease in population from year to year? 

In [84]:
#extract the population column to be a new array
#use diff to find the difference between each two years.
pop = nyc_water[:,1]
pop_diff = np.diff(pop, n = 2)